### ISSUE TITLE
bfdocs server has no method configure

### ISSUE THREAD

**Issue by Xaviju** [beautiful-docs/beautiful-docs#45]
Just started with beautiful docs, ahnd created an example manifest.json as in doc example

> bfdocs --server --watch manifest.json

Generating documentation from manifest 'manifest.json'
[]
[]
Starting server on port 8080

/usr/lib/node_modules/beautiful-docs/lib/index.js:77
    app.configure(function() {
        ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
  at Object.exports.serveStaticDir (/usr/lib/node_modules/beautiful-docs/lib/index.js:77:9)
  at startServer (/usr/lib/node_modules/beautiful-docs/lib/command.js:115:21)
  at /usr/lib/node_modules/beautiful-docs/lib/command.js:161:18
  at /usr/lib/node_modules/beautiful-docs/lib/generator.js:290:18
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:254:17
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:157:25
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:251:21
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:615:34
  at /usr/lib/node_modules/beautiful-docs/lib/generator.js:384:18
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:254:17
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:157:25
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:251:21
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:615:34
  at done (/usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:135:19)
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:32:16
  at /usr/lib/node_modules/beautiful-docs/lib/generator.js:384:18
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:254:17
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:157:25
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:251:21
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:615:34
  at done (/usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:135:19)
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:32:16
  at /usr/lib/node_modules/beautiful-docs/lib/generator.js:384:18
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:254:17
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:157:25
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:251:21
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:615:34
  at done (/usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:135:19)
  at /usr/lib/node_modules/beautiful-docs/node_modules/async/lib/async.js:32:16
  at Object.oncomplete (fs.js:107:15)

**Comment by jasonb-vbt** [comment]
Just hit this issue myself. Did you ever find a workaround for it? Like some quick hack to index.js or something?
