### ISSUE TITLE
Express 4.x breaks bfdocs --server

### ISSUE THREAD

**Issue by jdhoek** [beautiful-docs/beautiful-docs#47]
After NPM installing `bfdocs`, the `--server` option exits with an error:

```
Starting server on port 8080

/home/freaknl/.local/share/npm/lib/node_modules/beautiful-docs/lib/index.js:77
    app.configure(function() {
        ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
  at Object.exports.serveStaticDir (/home/freaknl/.local/share/npm/lib/node_modules/beautiful-docs/lib/index.js:77:9)
  at startServer (/home/freaknl/.local/share/npm/lib/node_modules/beautiful-docs/lib/command.js:115:21)
```

The cause appears to be the removal of the `configure` method from `express >= 4`.

A short term solution would probably mean limiting `express` to pre-4.x releases in `package.json`.

**Comment by jasonb-vbt** [comment]
Did you ever find a workaround for this issue? Even just a quick hack to index.js, just enough so the thing will run so I can evaluate beautiful-docs for use in our project, would be great.

**Comment by jdhoek** [comment]
Nope, I have not found a workaround for this issue.
